import SitePage,{Section,Cards} from './SitePage';

const source='https://eitfaridabad.com';

const DATA={
 about:{title:'About Echelon',intro:'Since its inception in 2007, Echelon Institute of Technology has been driven by a singular vision to pioneer experiential education that transcends conventional boundaries.',sections:[['About EIT',`Echelon Institute of Technology (EIT), Faridabad, established in 2007, is a premier institution dedicated to academic excellence, innovation, and holistic development. Affiliated to Guru Gobind Singh Indraprastha University (GGSIPU), EIT combines academic credibility with mentorship, personalised attention and an outcome-based learning ecosystem.`],['Vision',`Technical and Management leaders engaged in the evolution of life, being at the frontiers of the continuous technological and administrative breakthroughs, inspired by ongoing exploration of self, society, and nature through self-reflective consciousness by building a culture of inspiration, exploration and growth.`],['Mission',['Having a culture of inspiration, exploration, and invention through effective, experiential teaching-learning giving rise to ever-evolving knowledge and wisdom.','To have self-inspired students ever engaged in continually working upon & sharpening and deepening computational, creative, innovative, & leadership consciousness.','Having students established in self-reflective consciousness, committed to personal, social and human integrity, and engaged in deep inquiry and conversation, giving rise to shared, intersubjective human values and consciousness.']]]},
 chairman:{title:"Chairman's Message",intro:'A message from the leadership of Echelon Institute of Technology.',sections:[['Leadership',`Echelon's philosophy places experiential learning, inspiration, exploration and growth at the centre of institutional development. The institute aims to prepare students to contribute meaningfully to technology, management, industry and society.`]]},
 director:{title:"Director's Message",intro:'Leadership perspective on education, innovation and student development.',sections:[['Message',`The institute works toward building future-ready professionals through outcome-based education, practical exposure, industry interaction, research and continuous skill development.`]]},
 org:{title:'Organisational Structure',intro:'Institutional governance and academic administration at EIT.',sections:[['Structure',['Management and leadership','Academic departments','Training & Placement','Quality Assurance','Research & Development','Student clubs, societies and support cells']]]},
 governors:{title:'Board Of Governors',intro:'Institutional governance and representatives.',sections:[['Board',`The Board of Governors provides institutional direction and oversight across academic, administrative, quality and development priorities.`]]},
 approvals:{title:'Affiliations & Approvals',intro:'EIT is affiliated to GGSIPU and approved by AICTE, with accreditation and industry collaboration initiatives.',sections:[['Accreditations',['Approved by AICTE','Affiliated to Guru Gobind Singh Indraprastha University (GGSIPU), Delhi','NBA accreditation for B.Tech CSE','Industry collaborations and Centres of Excellence']]]},
 iso:{title:'ISO & Certifications',intro:'Quality systems, institutional certifications and recognitions.',sections:[['Quality',`EIT follows institutional quality practices aimed at continuous improvement in academic and administrative processes.`]]},
 philosophy:{title:'Philosophy We Live By',intro:'Inspiration, exploration, invention and growth.',sections:[['Our Philosophy',`Education at Echelon is approached as an experiential journey that develops technical capability, reflective awareness, leadership, creativity and a sense of responsibility toward society.`]]},
 programmes:{title:'Programmes Offered',intro:'Academic programmes currently presented by EIT.',sections:[['Engineering & Technology',['B.Tech in Computer Science & Engineering','B.Tech in Artificial Intelligence & Data Science','B.Tech in Robotics & Artificial Intelligence','B.Tech in Mechatronics Engineering','B.Tech(CSE) in AI & Machine Learning','B.Tech(CSE) in Cyber Security','B.Tech(CSE) in Data Science','B.Tech(CSE) in Internet Of Things And Cyber Security Including Block Chain Technology','B.Tech in Civil Engineering','B.Tech in Mechanical Engineering','B.Tech in Electronics & Communication Engineering','M.Tech in Computer Science & Engineering (CSE)']],['Management & Computer Applications',['BBA General','BBA in Digital Marketing','BBA in Financial Services','Master of Business Administration (MBA)','BCA General','BCA in Data Science','Master of Computer Applications']]]},
 academic:{title:'Academic Calendar',intro:'Academic scheduling, semester activities and institutional academic planning.',sections:[['Academic Planning',`Academic activities follow the university calendar and institutional schedules. Students should use the latest official notice/calendar issued by EIT for dates and changes.`]]},
 scheme:{title:'Scheme Calendar',intro:'Schemes, syllabi and academic process resources.',sections:[['Resources',['Schemes & Syllabus','Academic Calendar','Programme curriculum','Examination-related information']]]},
 nba:{title:'Policy–Program–Process: NBA & NAAC Perspective',intro:'Quality-oriented programme and process framework.',sections:[['Framework',`The institutional quality framework connects programme outcomes, teaching-learning processes, assessment, continuous improvement, documentation and stakeholder feedback.`]]},
 why:{title:'Why Echelon',intro:'An invitation to the culture of inspiration, exploration, invention and growth.',sections:[['Why Study at Echelon',['Industry-integrated learning','80+ laboratories and learning facilities','50+ PhD faculty members','Industry partnerships','Experiential and outcome-based education','Student clubs and communities']]]},
 brochure:{title:'Admission Brochure',intro:'Admission information and programme details for prospective students.',sections:[['Admissions',['Programme information','Eligibility criteria','Fee structure','Scholarship information','Admission procedure']]]},
 procedure:{title:'Admission Procedure',intro:'The eligibility criteria, merit and procedure are subject to guidelines issued by the concerned authorities.',sections:[['B.Tech',['Duration: 4 Years','Computer Science Engineering','Electronics & Communication Engineering','Mechanical Engineering','Civil Engineering','B.Tech CSE in Artificial Intelligence & Machine Learning','B.Tech CSE in Data Science']],['B.Tech (LEET)',['Duration: 3 Years','Computer Science Engineering','Electronics & Communication Engineering','Mechanical Engineering']]]},
 checklist:{title:'Document Check List',intro:'Documents required for admission and verification.',sections:[['Checklist',['Academic qualification documents','Identity proof','Photographs','Category/certificate documents where applicable','Transfer/migration documents where applicable','Fee and admission documents']]]},
 eligibility:{title:'Eligibility Criteria',intro:'Programme-specific eligibility information.',sections:[['B.Tech',`10+2 with Physics and Mathematics as compulsory subjects along with an approved additional subject. Current admission criteria and category relaxations remain subject to university/government guidelines.`]]},
 refund:{title:'Refund Policy',intro:'Admission and fee refund framework.',sections:[['Policy',`Refunds are governed by the applicable university, regulatory and institutional rules. Students should use the latest official policy for the current admission cycle.`]]},
 antiragging:{title:'Anti-Ragging',intro:'EIT maintains a zero-tolerance approach toward ragging.',sections:[['Student Safety',`Students are expected to follow institutional discipline and anti-ragging requirements. Complaints and support are handled through the designated institutional mechanisms.`]]},
 scholarship:{title:'Scholarship',intro:'Financial support and scholarship opportunities.',sections:[['Scholarships',`Eligible students may receive scholarships or financial support under applicable government, university and institutional schemes. Current eligibility and documentation requirements should be checked in the latest official notice.`]]},
 placement:{title:'Placement Cell',intro:'The Division of Training & Placement supports students in bridging academic learning and professional opportunities.',sections:[['Current Highlights',[`10,000+ placement offers`,`500 recruiting companies`,`80 hi-tech labs`,`52 LPA highest package`]],['Objectives',['Career Counseling and Guidance','Internship and Placement Facilitation','Pre-Placement Engagements','Building Corporate Connections']],['Vision',`The Training & Placement Division is dedicated in forging impactful and lasting collaborations with leading organizations across a spectrum of industries.`],['Mission',`To transform every student's journey into a Launchpad for success—ensuring they graduate not only with a degree that reflects academic brilliance but also with a career opportunity that resonates with their passion and goals.`]]},
 placementVision:{title:'Placement Vision & Mission',intro:'A dynamic ecosystem of industry collaboration and career opportunities.',sections:[['Vision',`Forge impactful and lasting collaborations with leading organizations and create transformative internship and placement opportunities.`],['Mission',`Transform every student's journey into a launchpad for success with academic excellence and meaningful career opportunities.`]]},
 placementHead:{title:'Message from Head-T & P',intro:'Training & Placement leadership message.',sections:[['Message',`The Training & Placement Division works continuously to improve employability through industrial visits, expert lectures, workshops, aptitude development, mock interviews and industry interaction.`]]},
 placementPolicy:{title:'Policy of Placement',intro:'Structured, transparent and equitable placement ecosystem.',sections:[['Purpose',`The Placement Policy governs the process from student registration to final job offer while upholding fairness, integrity and industry alignment.`],['Key Definitions',['Division of Training & Placement','Placement Consent Form','On-Campus Placement','Off-Campus Placement','Placement Drive']]]},
 research:{title:'Research & Development',intro:'Research, innovation and knowledge creation across the institution.',sections:[['R&D Committee',`The R&D ecosystem supports faculty and student research, publications, projects, intellectual property and external collaboration.`],['Research Areas',['Artificial Intelligence & Machine Learning','Data Science','Cyber Security','IoT and Blockchain','Electronics and Communication','Mechanical and Civil Engineering','Management and Applied Sciences']]]},
 virtual:{title:'Virtual Tour',intro:'Explore the Echelon campus and institutional facilities.',sections:[['Campus',['Academic blocks','Engineering laboratories','Centres of Excellence','Central library','Seminar halls and auditorium','Sports complex']]]},
 career:{title:'Career @ EIT',intro:'Join Echelon Institute of Technology.',sections:[['Application',['Basic Information','Education','Experience','Research Publications','Resume upload']],['Experience & Research',['Teaching Experience','Industry Experience','Current Salary','Scopus/SCI research papers']]]},
 iqac:{title:'Internal Quality Assurance Cell (IQAC)',intro:'The IQAC drives continuous improvement in institutional academic and administrative performance.',sections:[['Objectives',['Enhance Quality Culture','Continuous Improvement','Stakeholder Engagement','Innovative Practices']],['Quality Policy',`The IQAC is committed to academic excellence, continuous improvement and institutional integrity through teaching-learning quality, research and industry collaboration, feedback, audits and holistic development.`],['Head IQAC','Prof. Sunil Verma, Head IQAC.']]},
 nirf:{title:'NIRF 2026',intro:'National Institutional Ranking Framework information and institutional submissions.',sections:[['NIRF Documents',['Overall Category DCS Report – NIRF','Engineering Category DCS Report – NIRF','Sustainable Institutions DCS Report – NIRF']],['Nodal Officer','Prof. Sunil Verma · +91 9910788932']]},
 notices:{title:'Circulars / Notices',intro:'Current institutional notices and announcements.',sections:[['Current Notices',['AIML Training ISA University','Special Chance for Exam','Commencement of Even Sem 2025-26 Classes','Fee for Notice']]]},
 disclosure:{title:'Mandatory Disclosure',intro:'Mandatory institutional information and regulatory disclosures.',sections:[['Organisation Info',['Name: Echelon Institute of Technology','Village: Kabulpur, Jasana-Manjhawali Road, Faridabad-121001, Haryana','Office hours: 8:50 AM to 4:15 PM','Academic hours: 8:50 AM to 4:15 PM','Type: Private-Self Financed · Co-Ed']],['Director','Dr. Arvind Kumar Pandey, Ph.D.']]},
 grievance:{title:'Grievance Redressal',intro:'Institutional mechanisms for student and stakeholder grievances.',sections:[['Support',['Grievance Portal','Grievance Redressal Committee','Internal Committee / Women Cell','SC/ST Cell']]]},
 iic:{title:"Institution's Innovation Council",intro:'Innovation, entrepreneurship and student-driven problem solving.',sections:[['Innovation Ecosystem',['Innovation projects','Hackathons','Entrepreneurship activities','Industry and research interaction']]]},
 society:{title:'Professional Society',intro:'Student communities and professional engagement.',sections:[['Communities',['Yuva Kreeda Society','Kshitij Cultural Society','Samvedna Society','Technovation Club','The Computer Club','Literary Society','NSS (National Service Scheme)']]]},
 library:{title:'EIT Library',intro:'Centralised academic resources and learning support.',sections:[['Facilities',['Central Library','Digital learning resources','Academic books and publications','Reference resources']]]},
 events:{title:'Events @ Echelon',intro:'Institutional events, conferences, summits and student activities.',sections:[['Current / Featured Events',['INTERNATIONAL CONFERENCE ICASTSD-VIRTUAL 29-30 May 2026','MEGA JOB FAIR','PRINCIPAL SUMMIT','HACKINDIA HACKATHON','INDIAN KNOWLEDGE SYSTEM (IKS)','SHARK TANK @ECHELON','HR CONCLAVE','SCIENCE EXHIBITION','DIGITAL LITERACY AND SKILL INDIA INITIATIVES','FACULTY DEVELOPMENT PROGRAMS','THANKSGIVING CELEBRATIONS','PRASHASTI STUDENTS RECOGNITION DAY']]]},
 podcasts:{title:'Podcasts & Talks',intro:'Knowledge beyond classrooms through conversations, talks and expert interactions.',sections:[['Knowledge Beyond Classrooms',`The institution presents conversations and talks that extend learning beyond the classroom and expose students to professional and social perspectives.`]]},
 shooting:{title:'Shooting @ Echelon',intro:'Filmed on campus.',sections:[['Campus Productions',['College Romance — Season 1 & 2','Popular TV Serial','Lucky Guy']]]},
 celebrities:{title:'Celebrities @ EIT',intro:'Artists and public personalities who have been featured at EIT.',sections:[['Featured',['Maninder Buttar','Babbal Rai','Raftaar','Jassie Gill','Harrdy Sandhu','Millind Gaba']]]},
 achievers:{title:'Our Achievers',intro:'Sparkling brilliance in academics and student achievement.',sections:[['Academic Achievers',['Ankit Kumar — B.Tech (AIML)','Lalit — B.Tech (AIML) — 9.027 SGPA','Krishan — B.Tech (AIML) — 8.811 SGPA','Isha Giri — B.Tech (AIML) — 8.541 SGPA','Pakhi Sharma — B.Tech (AIML) — 8.378 SGPA','Rohit Kumar — B.Tech (ECE) — 8.757 SGPA','Vaibhav Chawla — B.Tech (CSE) — 9.282 SGPA','Yash — B.Tech (CSE) — 8.872 SGPA','Neha Singh — B.Tech (CSE) — 9.208 SGPA','Pawan Bhati — B.Tech (CSE) — 9.208 SGPA']]]},
 sports:{title:'Sports Achievers',intro:'Student participation and achievement in sports.',sections:[['Highlights',['Aravali 2025','Rawfest Rawal 2026','Astititva ADGIP 2026','IIT Kanpur Udghosh 2025']]]}
};

function renderSection(title,content){return <Section id={`section-${renderSection.i++}`} title={title}>{Array.isArray(content)?<Cards items={content}/>:<p>{content}</p>}</Section>}
export function InstitutionalPage({page}){renderSection.i=0;const d=DATA[page]||DATA.about;return <SitePage title={d.title} intro={d.intro} links={[[`Open current EIT source ↗`,source]]}>{d.sections.map(([t,c],i)=><div key={i}>{renderSection(t,c)}</div>)}</SitePage>}
export const pageKeys=Object.keys(DATA);
export {DATA};
